const ALERT = "ALERT";
const REFETCH_CHATS = "REFETCH_CHATS";
const NEW_ATTACHMENT = "NEW_ATTACHMENT";
const NEW_MESSAGE_ALERT = "NEW_MESSAGE_ALERT";
const NEW_REQUEST = "NEW_REQUEST";
const NEW_MESSAGE = "NEW_MESSAGE";
const JOIN_CHAT = "JOIN_CHAT";
const LEAVE_CHAT = "LEAVE_CHAT";
const START_TYPING = "START_TYPING";
const STOP_TYPING = "STOP_TYPING";
const USER_ONLINE = "USER_ONLINE";
const USER_OFFLINE = "USER_OFFLINE";
const CALL = "CALL";
const ONGOING_CALL = "ONGOING_CALL";
const WEB_RTC_SIGNAL = "WEB_RTC_SIGNAL";
const HANG_UP = "HANG_UP"

export {
  ALERT,
  REFETCH_CHATS,
  NEW_ATTACHMENT,
  NEW_MESSAGE_ALERT,
  NEW_REQUEST,
  NEW_MESSAGE,
  JOIN_CHAT,
  LEAVE_CHAT,
  START_TYPING,
  STOP_TYPING,
  USER_ONLINE,
  USER_OFFLINE,
  CALL,
  ONGOING_CALL,
  WEB_RTC_SIGNAL,
  HANG_UP
};
